config/routes.rb
Rails.application.routes.draw do
  resources :formulas
  resources :statistics
  resources :indicators
  resources :subthemes
  resources :themes
  resources :reasons
  resources :topics
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to:'pages#dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="parallax">
  <h1 class="text-center">Indicadores de la Iniciativa Ciudades <br>
  Emergentes y Sostenibles</h1>
  <br>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div style="padding-top: 150px;">
  <div class="footer2">
    <div class="container text-center " style="padding-top: 8px; padding-bottom: 8px;" >
      <a href="http://www.leonardoluxburg.com">
        <%= image_tag "lllogo.png" %>
      </a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon fixed-top">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "LogoMakr_6SNA21.png" %>
  <% end %>
  <div class="dropdown ">
    <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
    <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
      <li> <a href="/"> <p> <i style="padding-left: 10px;"class="fas fa-home"></i> Home</p></a></li>
      <li><%= link_to topics_path do %> <i style="padding-left: 10px;"class="fas fa-file-alt"></i> Indicadores</p><% end %></li>
      <li><%= link_to statistics_path do %> <p><i style="padding-left: 10px;"class="fas fa-chart-bar"></i> Estadisticas</p><% end %></li>
      <li><a href="/"><p><i style="padding-left: 10px;"class="fas fa-phone-volume"></i> Contacto</p></a></li>
      <% if user_signed_in? %>
      <li><a href="/dashboard"><p><i style="padding-left: 10px;"class="fas fa-tools"></i></i> Dashboard</p></a></li>
      <%= link_to destroy_user_session_path, method: :delete do %>
      <p><i style="padding-left: 10px;"class="fas fa-sign-out-alt"></i> Salir</p>
      <% end %>
      <% end %>
    </ul>
  </div>
</div>