config/routes.rb
Rails.application.routes.draw do
  resources :formulas
  resources :statistics
  resources :indicators
  resources :subthemes
  resources :themes
  resources :reasons
  resources :topics
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to:'pages#dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/reason.rb
class Reason < ApplicationRecord
  belongs_to :topic
  has_many :themes, dependent: :destroy
end

app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
  before_action :set_reason, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index, :show]

  # GET /reasons
  # GET /reasons.json
  def index
    @reasons = Reason.all
  end

  # GET /reasons/1
  # GET /reasons/1.json
  def show
  end

  # GET /reasons/new
  def new
    @reason = Reason.new
  end

  # GET /reasons/1/edit
  def edit
  end

  # POST /reasons
  # POST /reasons.json
  def create
    @reason = Reason.new(reason_params)

    respond_to do |format|
      if @reason.save
        format.html { redirect_to @reason, notice: 'Reason was successfully created.' }
        format.json { render :show, status: :created, location: @reason }
      else
        format.html { render :new }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reasons/1
  # PATCH/PUT /reasons/1.json
  def update
    respond_to do |format|
      if @reason.update(reason_params)
        format.html { redirect_to @reason, notice: 'Reason was successfully updated.' }
        format.json { render :show, status: :ok, location: @reason }
      else
        format.html { render :edit }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reasons/1
  # DELETE /reasons/1.json
  def destroy
    @reason.destroy
    respond_to do |format|
      format.html { redirect_to reasons_url, notice: 'Reason was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reason
      @reason = Reason.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reason_params
      params.require(:reason).permit(:title, :description, :topic_id)
    end
end

app/views/reasons/_form.html.erb
<h4>Categoria</h4>
<hr>
<%= simple_form_for(@reason) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.association :topic %>
  </div>

  <div class="form-actions">
    <%= f.button :submit,  class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reasons/edit.html.erb
<div class="container" style="padding-top: 150px; ">

<h1>Editing Reason</h1>

<%= render 'form', reason: @reason %>

<%= link_to 'Show', @reason %> |
<%= link_to 'Destroy', @topic, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', reasons_path %>
</div>

app/views/reasons/index.html.erb
<div class="header">
  <div class="container">
    <div class="row">
      <div class="header-links">
        <ul>
          <li><a href="/topics">CATEGORIAS</a></li>
          <li><a href="/reasons">PILARES</a></li>
          <li><a href="/themes">TEMAS</a></li>
          <li><a href="/subthemes">SUBTEMAS</a></li>
          <li><a href="/indicators">INDICADORES</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="header-title">
      <h2>Indicadores de la Iniciativa Ciudades
      Emergentes y Sostenibles</h2>
    </div>
  </div>
</div>
<div class="container" style="margin-top: 10px;">
  <p id="notice"><%= notice %></p>
  <h2>Pilares</h2>
  <hr>
  <div class="table">
    <div class="table-content">
     <% @reasons.each do |indicator| %>
     <div class="topic">
      <%= link_to indicator do %>

      <h3>· <%= indicator.title %></h3>

      <% end %>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/reasons/new.html.erb
<div class="container" style="padding-top: 150px; ">

<h1>New Reason</h1>

<%= render 'form', reason: @reason %>
<hr>
<%= link_to 'Back', reasons_path %>
</div>

app/views/reasons/show.html.erb
<div class="header">
  <div class="container">
    <div class="row">
      <div class="header-links">
        <ul>
          <li><a href="/topics">CATEGORIAS</a></li>
          <li><a href="/reasons">PILARES</a></li>
          <li><a href="/themes">TEMAS</a></li>
          <li><a href="/subthemes">SUBTEMAS</a></li>
          <li><a href="/indicators">INDICADORES</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="header-title">
      <h2>Indicadores de la Iniciativa Ciudades
      Emergentes y Sostenibles</h2>
    </div>
  </div>
</div>
<div class="container" style="margin-top: 10px;">
  <p id="notice"><%= notice %></p>
  <h2><%= @reason.topic.title %></h2>
  <hr>
  <div class="table">
    <div class="table-content">
      <div class="topic">
        <h3><%= @reason.title %></h3>
        <p style="font-size: 15px; "><%= @reason.description %></p>
        <h5>Temas <i class="fas fa-angle-down" data-toggle="collapse" data-target="#demo1"></i></h5>
        <div id="demo1" class="collapse">
          <% @reason.themes.each do |theme| %>
          <%= link_to theme do %>
          <h6><%= theme.title %></h6>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>