config/routes.rb
Rails.application.routes.draw do
  resources :formulas
  resources :statistics
  resources :indicators
  resources :subthemes
  resources :themes
  resources :reasons
  resources :topics
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to:'pages#dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/dashboard.html.erb
<div class="jumbotron text-center" style="margin-bottom:0">
  <h3>Indicadores de la Iniciativa Ciudades <br>
  Emergentes y Sostenibles</h3>
  <p>Dashboard</p>
</div>
<div class="container" style="margin-top:30px">
  <div class="row">
    <div class="col-sm-3">
      <br>
      <h3>Configurar</h3>
      <p>Editar informacion</p>
      <ul class="nav nav-tabs flex-column">
        <li class="nav-item">
          <a class="nav-link active" data-toggle="tab" href="#home">Data</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#menu1">Indicators</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" data-toggle="tab" href="#menu2">User</a>
        </li>
      </ul>
      <hr class="d-sm-none">
    </div>
    <div class="col-sm-9">
      <div class="tab-content">
        <div id="home" class="container tab-pane active"><br>
          <h2>Estadisticas</h2>
          <hr>
          <% @stats.each do |s| %>

          <p><%= s.id %> <%= s.title %> | <%= s.value %> <br> <%= link_to 'Show', s %> | <%= link_to 'Edit', edit_statistic_path(s) %> | <% link_to 'Destroy', s, method: :delete, data: { confirm: 'Are you sure?' } %></p>

          <% end %>
        </div>
        <div id="menu1" class="container tab-pane fade"><br>
          <h2>Indicadores</h2>
          <hr>
          <% @indicators.each do |i| %>

          <p><%= i.id %> <%= i.title %>  <br> <%= link_to 'Show', i %> | <%= link_to 'Edit', edit_indicator_path(i) %> | <% link_to 'Destroy', i, method: :delete, data: { confirm: 'Are you sure?' } %></p>

          <% end %>
        </div>
        <div id="menu2" class="container tab-pane fade"><br>
         <h2>Inf. de Usuario</h2>
         <br>
         <p>Email: <br>  <%= current_user.email %></p>
         <p>Autorizaciones: <br> Admin</p>
       </div>
     </div>

   </div>
 </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,0,0,0.6) 0%, rgba(0,0,0,0.7) 50%), url('<%= image_path('chepomap.png')%>');">
  <div>
    <div class="hidden-xs hidden-sm">
      <%= image_tag "LogoMakr_6SNA21.png" %>
    </div>
    <br>
    <h3>Indicadores de la Iniciativa Ciudades <br>
      Emergentes y Sostenibles</h3>
  </div>
</div>
<div class="container" style="padding-top: 150px;" >
  <h1 class="text-center" style="">Sobre el Proyecto</h1>
  <hr>
  <br>
  <p class="text-center" style="font-size: 1.2em;  ">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut dolore deserunt voluptate possimus! Impedit ullam illo deleniti facere quasi ad, neque numquam atque aliquid necessitatibus, est aspernatur modi suscipit obcaecati.</p>

  <p class="text-center" style="font-size: 1.2em;  ">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Iste voluptates exercitationem ut. Eligendi veniam qui molestiae provident tenetur doloremque, facere dignissimos atque modi. Quidem harum, repellat accusamus laboriosam aperiam sint!</p>

  <br>
  <hr>
</div>
<div class="container text-center" style="padding-top: 40px;" >
  <br>
<div class="form-group">
    <label for="" class="sr-only"></label>
    <input type="text" class="form-control" id="inputPassword2" placeholder="Indicador">
</div>
 <a href="/indicators"><button type="submit" class="btn btn-primary mb-2 text-center">Buscar</button></a>
  <br>
</div>
<div class="container" style="padding-top: 150px; ">
  <div class="row">
    <div class="col-xs-12 col-md-4 text-center">
      <i class="fas fa-leaf" style="font-size:120px; color: #25527A;"></i>
      <br>
      <br>
      <h3 class="text-center" style=" ">Sostenibilidad Ambiental y <br>Cambio Climático</h3>
      <br>
      <p style="font-size: 1.0em;  " >Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eum qui autem nemo tenetur voluptates.</p>
      <a href="/topics"><p class="btn btn-primary">Explorar</p></a>
    </div>
    <div class="col-xs-12 col-md-4 text-center">
      <i class="fas fa-building"style="font-size:120px; color: #25527A;"></i>
      <br>
      <br>
      <h3 class="text-center" style="">Sostenibilidad <br> Urbana</h3>
      <br>
      <p style="font-size: 1.0em;  " >Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda beatae ea ullam temporibus possimus totam quis illo.</p>
     <a href="/topics"><p class="btn btn-primary">Explorar</p></a>
    </div>
    <div class="col-xs-12 col-md-4 text-center">
      <i class="fas fa-balance-scale" style="font-size:120px; color: #25527A;"></i>
      <br>
      <br>
      <h3 class="text-center" style=" ">Sostenibilidad Fiscal y Gobernabilidad</h3>
      <br>
      <p style="font-size: 1.0em;  " > Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusantium deserunt laudantium quibusdam quo eius? Eius similique consectetur.</p>
     <a href="/topics"><p class="btn btn-primary">Explorar</p></a>
    </div>
  </div>
</div>
<div class="container text-center " style="padding-top: 150px" id="q&a">
  <h1 style="">Temas</h1>
  <hr>
  <br>
    <p>
      <% @themes.each do |theme| %>
        <%= link_to theme do %>

         <%= theme.title %> |
        <% end %>
      <% end %>
    </p>
  <br>
  <hr>
</div>