config/routes.rb
Rails.application.routes.draw do
  resources :formulas
  resources :statistics
  resources :indicators
  resources :subthemes
  resources :themes
  resources :reasons
  resources :topics
  devise_for :users
  root to: 'pages#home'
  get '/dashboard', to:'pages#dashboard'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/indicator.rb
class Indicator < ApplicationRecord
  belongs_to :subtheme
  has_many :formulas
  has_many :statistics, through: :formulas
end

app/controllers/indicators_controller.rb
class IndicatorsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_indicator, only: [:show, :edit, :update, :destroy]

  # GET /indicators
  # GET /indicators.json
  def index
    @indicators = Indicator.all
  end

  # GET /indicators/1
  # GET /indicators/1.json
  def show
  end

  # GET /indicators/new
  def new
    @indicator = Indicator.new
  end

  # GET /indicators/1/edit
  def edit
  end

  # POST /indicators
  # POST /indicators.json
  def create
    @indicator = Indicator.new(indicator_params)

    respond_to do |format|
      if @indicator.save
        format.html { redirect_to @indicator, notice: 'Indicator was successfully created.' }
        format.json { render :show, status: :created, location: @indicator }
      else
        format.html { render :new }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /indicators/1
  # PATCH/PUT /indicators/1.json
  def update
    respond_to do |format|
      if @indicator.update(indicator_params)
        format.html { redirect_to @indicator, notice: 'Indicator was successfully updated.' }
        format.json { render :show, status: :ok, location: @indicator }
      else
        format.html { render :edit }
        format.json { render json: @indicator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /indicators/1
  # DELETE /indicators/1.json
  def destroy
    @indicator.destroy
    respond_to do |format|
      format.html { redirect_to indicators_url, notice: 'Indicator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_indicator
      @indicator = Indicator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def indicator_params
      params.require(:indicator).permit(:title, :description, :methodology, :positive, :negative, :medium, :unit, :value, :rate, :result, :justification, :other, :subtheme_id)
    end
end

app/views/indicators/_form.html.erb
<h4>Indicador</h4>
<hr>
<%= simple_form_for(@indicator) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :methodology %>
    <%= f.input :positive %>
    <%= f.input :negative %>
    <%= f.input :medium %>
    <%= f.input :unit %>
    <%= f.input :value %>
    <%= f.input :rate %>
    <%= f.input :result %>
    <%= f.input :justification %>
    <%= f.input :other %>
    <%= f.association :subtheme %>
  </div>

  <div class="form-actions">
    <%= f.button :submit , class: "btn btn-primary" %>
  </div>
<% end %>

app/views/indicators/edit.html.erb
<div class="container" style="padding-top: 150px; ">

<h1>Editing Indicator</h1>
<hr>
<br>
<%= simple_form_for(@indicator) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
<h3 class="text-center"><%= @indicator.title %></h3>
<br>
<p>
  <strong>Stadisticas:</strong>
    <br>
    <% @indicator.statistics.each do |x| %>
    <%= x.title %> | <%= x.value %> <br>
   <%= link_to 'Edit', edit_indicator_path(@indicator) %> <br>
    <% end %>
</p>

  <div class="form-inputs">

    <%= f.input :result %>

  </div>

  <div class="form-actions">
    <%= f.button :submit , class: "btn btn-primary" %>
  </div>
<% end %>

<%= link_to 'Show', @indicator %> |
<%= link_to 'Back', indicators_path %>
</div>

app/views/indicators/index.html.erb
<div class="header">
  <div class="container">
    <div class="row">
      <div class="header-links">
        <ul>
          <li><a href="/topics">CATEGORIAS</a></li>
          <li><a href="/reasons">PILARES</a></li>
          <li><a href="/themes">TEMAS</a></li>
          <li><a href="/subthemes">SUBTEMAS</a></li>
          <li><a href="/indicators">INDICADORES</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="header-title">
      <h2>Indicadores de la Iniciativa Ciudades
      Emergentes y Sostenibles</h2>
    </div>
  </div>
</div>
<div class="container" style="margin-top: 10px;">
  <p id="notice"><%= notice %></p>
  <h2>Indicadores</h2>
  <hr>
  <div class="table">
    <div class="table-content">
     <% @indicators.each do |indicator| %>
     <div class="topic">
      <%= link_to indicator do %>

      <h3>· <%= indicator.title %></h3>
      <% end %>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/indicators/new.html.erb
<div class="container" style="padding-top: 150px; ">

<h1>Nuevo Indicador</h1>

<%= render 'form', indicator: @indicator %>
<hr>
<%= link_to 'Back', indicators_path %>
</div>
<br>
</div>

app/views/indicators/show.html.erb
<div class="header">
  <div class="container">
    <div class="row">
      <div class="header-links">
        <ul>
          <li><a href="/topics">CATEGORIAS</a></li>
          <li><a href="/reasons">PILARES</a></li>
          <li><a href="/themes">TEMAS</a></li>
          <li><a href="/subthemes">SUBTEMAS</a></li>
          <li><a href="/indicators">INDICADORES</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="header-title">
      <h2>Indicadores de la Iniciativa Ciudades
      Emergentes y Sostenibles</h2>
    </div>
  </div>
</div>
<div class="container" style="margin-top: 10px;">
  <p id="notice"><%= notice %></p>
  <h2><%= @indicator.subtheme.title %></h2>
  <hr>
  <div class="table">
    <div class="table-content">
      <div class="topic">
        <h3 class="text-center"><%= @indicator.title %></h3>
        <br>
        <div style="">
          <% if @indicator.id == 1 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 1} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 2} %>
          <% x = (x1[0].value / x2[0].value) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 2 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 3} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 4} %>
          <% x = (x1[0].value / x2[0].value)  %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> </p>
          <% elsif @indicator.id == 5 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 5} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 6} %>
          <% x = ((x1[0].value - x2[0].value) / x1[0].value) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 7 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 7} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 2} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 8 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 8} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 9} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 9 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 10} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 2} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 11 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 11} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 12} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 14 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 13} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 12} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 15 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 14} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 12} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 16 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 15} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 12} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 17 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 16} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 2} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 18 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 17} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 2} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 20 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 18} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 19} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 21 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 20} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 2} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <% x = (@indicator.statistics[0].value / @indicator.statistics[1].value) %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> kWh</p>
          <% elsif @indicator.id == 23 %>
          <p class="text-center" style="font-size: 40px;"><%= @indicator.result %></p>
          <% elsif @indicator.id == 24 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 21} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 22} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> %</p>
          <% elsif @indicator.id == 25 %>
          <p class="text-center" style="font-size: 40px;"><%= @indicator.result %></p>
          <% elsif @indicator.id == 28 %>
          <p class="text-center" style="font-size: 40px;"><%= @indicator.result %></p>
          <% elsif @indicator.id == 29 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 23} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 24} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> CO2</p>
          <% elsif @indicator.id == 30 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 23} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 25} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> kg/US$</p>
          <% elsif @indicator.id == 31 %>
          <p class="text-center" style="font-size: 40px;"><%= @indicator.result %></p>
          <% elsif @indicator.id == 32 %>
          <p class="text-center" style="font-size: 40px;"><%= @indicator.result %></p>
          <% elsif @indicator.id == 33 %>
          <p class="text-center" style="font-size: 40px;"><%= @indicator.result %></p>
          <% elsif @indicator.id == 34 %>
          <p class="text-center" style="font-size: 40px;"><%= @indicator.result %></p>
          <% elsif @indicator.id == 35 %>
          <p class="text-center" style="font-size: 40px;"><%= @indicator.result %></p>
          <% elsif @indicator.id == 36 %>
          <p class="text-center" style="font-size: 40px;"><%= @indicator.result %></p>
          <% elsif @indicator.id == 38 %>
          <p class="text-center" style="font-size: 40px;"><%= @indicator.result %></p>
          <% elsif @indicator.id == 42 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 26} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 27} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> % </p>
          <% elsif @indicator.id == 43 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 28} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 2} %>
          <% x = (x1[0].value /  x2[0].value ) * 100 %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> % </p>
          <% elsif @indicator.id == 45 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 29} %>
          <% x = (x1[0].value /  100000 ) %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> % </p>
          <% elsif @indicator.id == 46 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 30} %>
          <% x = (x1[0].value /  100000 ) %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> % </p>
          <% elsif @indicator.id == 47 %>
          <p class="text-center" style="font-size: 40px;"><%= @indicator.result %></p>
           <% elsif @indicator.id == 48 %>
          <p class="text-center" style="font-size: 40px;"><%= @indicator.result %></p>
          <% elsif @indicator.id == 49 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 31} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 32} %>
          <% x3 = @indicator.statistics.select { |x| x['id'] == 24} %>
          <% x = ((x1[0].value - x2[0].value ) / x3[0].value ) * 100  %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> % </p>
          <% elsif @indicator.id == 50 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 33} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 2} %>
          <% x = (x1[0].value / x2[0].value ) * 100  %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> % </p>
          <% elsif @indicator.id == 58 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 34} %>
          <% x = (x1[0].value / 100000 ) %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> % </p>
          <% elsif @indicator.id == 60 %>
          <% x1 = @indicator.statistics.select { |x| x['id'] == 35} %>
          <% x2 = @indicator.statistics.select { |x| x['id'] == 24} %>
          <% x = (x1[0].value / x2[0].value ) * 100  %>
          <p class="text-center" style="font-size: 40px;"><%= x.round(2) %> % </p>
          <% else %>
          <div class="text-center">
            <p>On development</p>
          </div>
          <% end %>
        </div>
        <div class="container">
          <div class="row">
            <div class="col-md-4 text-center" >
              <i class="fas fa-frown" style=" color: #C90000; font-size: 75px;"></i> <br>
              <p style=" color: #25527A ;"><%= @indicator.negative %></p>
            </div>
            <div class="col-md-4 text-center">
              <i class="fas fa-meh" style=" color: #F2E200; font-size: 75px;"></i> <br>
              <p style=" color: #25527A ;" ><%= @indicator.medium %></p>
            </div>
            <div class="col-md-4 text-center" >
              <i class="fas fa-smile" style=" color: #18BA00; font-size: 75px;"></i> <br>
              <p style=" color: #25527A ;" ><%= @indicator.positive %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="description text-center">
       <br>
       <p>
        <strong>Stadisticas:</strong>
        <br>
        <% @indicator.statistics.each do |x| %>
        <%= x.title %> | <%= x.value %> <br>
        <% end %>
      </p>
      <p>
        <strong>Descripcíon:</strong>
        <br>
        <%= @indicator.description %>
      </p>
      <p>
        <strong>Metodologia:</strong>
        <br>
        <%= @indicator.methodology %>
      </p>
      <p>
        <strong>Justificacíon:</strong>
        <br>
        <%= @indicator.justification %>
      </p>

      <p>
        <strong>Otros:</strong>
        <br>
        <%= @indicator.other %>
      </p>
    </div>
  </div>
  </div>
 <% if user_signed_in? %>
  <p><%= link_to 'Edit', edit_indicator_path(@indicator) %></p>
  <% end %>
</div>